"""fix quantity

Revision ID: a7f342badbac
Revises: d6b90449bffd
Create Date: 2023-05-12 14:57:40.643280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f342badbac'
down_revision = 'd6b90449bffd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('quantity', sa.String(), nullable=True))
    op.alter_column('operation', 'instrument_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('operation', 'quanity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('quanity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('operation', 'instrument_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('operation', 'quantity')
    # ### end Alembic commands ###
